feat: forming structures for academy landing step 1
atls-academy/eshevlyakova.github.io pull request #11
Opened 2022-09-02 16:24 UTC by eshevlyakova

2022-09-02 16:29 UTC, eshevlyakova commented
@TFK70 
При запуске команды `yarn workspace @landing/index-page run dev`. Появляется следующая ошибка:
`ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: > Couldn't find a `pages` directory. Please create one under the project root`
Хотя у меня есть папка pages и она расположена там же, как и в примерах

2022-09-02 16:32 UTC, TFK70 commented
@eshevlyakova 

> Хотя у меня есть папка pages и она расположена там же, как и в примерах

В том то и дело что нет, не там же. Смотри внимательнее

2022-09-03 12:25 UTC, eshevlyakova commented
@TFK70 
Исправила структуру, но теперь при запуске команды `yarn workspace @landing/app run dev` появляется эта ошибка:
`It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Please install @types/react by running`
Хотя я же добавила @types/react в package.json

2022-09-03 12:27 UTC, TFK70 commented
@eshevlyakova нужно использовать эту версию: "@types/react": "18.0.1",

Чтобы везде на проекте использовалась только эта версия - добавь в корневой пекедж секцию resolutions и помести туда нужную зависимость с нужной версией

2022-09-03 12:34 UTC, eshevlyakova commented
@TFK70 
То есть я удаляю @types/react из всех package.json. А в глобальный/корневой package.json добавляю это:
```json
"resolutions": {
    "@types/node": "16",
    "@types/react": "18.0.1",
    "@types/react-dom": "17",
    "next": "12.1.0",
    "react": "17",
    "react-dom": "17"
  },
  "devDependencies": {
    "@atls/code-service": "^0.0.16",
    "@atls/config-jest": "^0.0.5",
    "@jest/core": "^28.1.2",
    "@types/eslint": "^8",
    "@types/jest": "^28.1.3",
    "@types/node": "^18.7.14",
    "@types/react": "18.0.1",
    "@types/react-dom": "^17.0.9",
    "eslint": "^8.18.0",
    "husky": "^8.0.1",
    "typescript": "^4.8.2"
  }
```

После этого такая же ошибка

2022-09-03 12:39 UTC, TFK70 commented
@eshevlyakova а, нет, проблема не в версии либы с типами

> То есть я удаляю @types/react из всех package.json. А в глобальный/корневой package.json добавляю это:

Удалять их не надо. Если ты их удалишь - их не будет совсем, а они тебе нужны, но с определенной версией. Поэтому ты их оставляешь и просто добавляешь в корневой пекедж этот пакет с нужной версией

Чтобы это пофиксить тебе нужен typescript@4.2.2, добавь его resolutions

2022-09-03 14:28 UTC, eshevlyakova commented
@TFK70 
Теперь все запускается. Только появилась новая ошибка: 
`error - ./pages/index.ts:1:0
Module not found: Can't resolve '@landing/index-page'
> 1 | export { default} from '@landing/index-page'`

Хотя у меня есть модуль @landing/index-page и он прописывается в landing/pages/index-page/package.json

2022-09-03 14:29 UTC, TFK70 commented
@eshevlyakova он должен быть как зависимость в воркспейсе где ты его используешь - https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/landing/app/package.json#L8

2022-09-03 14:40 UTC, eshevlyakova commented
@TFK70 

- Я могу в файлах с расширением .tsx писать код .jsx?
- При запуске появилась данная ошибка: 
`Module parse failed: Unexpected token (4:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`
На четвертой строке у меня return. Это значит, что мне нужно скачать какой-то пакет для обработки файлов .tsx?

2022-09-03 14:43 UTC, TFK70 commented
@eshevlyakova нет, это значит что ты сделала не всё как в примере, в тулзах вебпак настроен и ничего самостоятельно с ним делать не нужно

Как минимум у тебя отсутствует next.config

2022-09-03 16:06 UTC, eshevlyakova commented
@TFK70 
Теперь все запускается. Я правильно поняла, что:

- в pages/index-page/src/index.page.tsx я пишу главную страницу приложения
- чтоы запустить приложение и увидеть код, который я писала, нужно запустить: `yarn workspace @landing/app run dev`

2022-09-03 16:07 UTC, TFK70 commented
@eshevlyakova ну в общем-то да, все так

2022-09-06 10:28 UTC, eshevlyakova commented
@TFK70 
Как исправлять такого рода ошибки (их больше 20 наверно): `Error: No matching configuration found for /Users/j_sh/Desktop/landing/eshevlyakova.github.io/ui/input/src/label/label.styles.ts. `?
Как я поняла не хватает какой-то конфигурации

2022-09-06 11:05 UTC, TFK70 commented
> @TFK70 Как исправлять такого рода ошибки (их больше 20 наверно): `Error: No matching configuration found for /Users/j_sh/Desktop/landing/eshevlyakova.github.io/ui/input/src/label/label.styles.ts. `? Как я поняла не хватает какой-то конфигурации

Понятия не имею откуда она могла появиться, делай всегда коммит вместе с подобными комментариями, чтобы я сам запустить мог

2022-09-07 09:40 UTC, eshevlyakova commented
@TFK70 
Хочу разделить главную страницу на компоненты. Но при экспорте HeaderBlock появилась эта ошибка, не могу понять из-за чего: 
`error - ../../../.yarn/__virtual__/@landing-header-fragment-virtual-5d98ac56b6/1/landing/fragments/landing-header/src/index.ts
Module not found: Can't resolve './reviews.component' in '/Users/j_sh/Desktop/landing/eshevlyakova.github.io/.yarn/__virtual__/@landing-header-fragment-virtual-5d98ac56b6/1/landing/fragments/landing-header/src'`

И также из-за чего ошибка в главной странице в файле index.page.tsx 60 строка: `Incompatible element override from component`

И еще вопрос: как обнулять стили, к примеру для тега body? Нужно создавать файл css?

2022-09-07 09:49 UTC, TFK70 commented
@eshevlyakova 

Ошибка из-за того что у тебя нет файла `./reviews.component`

> И также из-за чего ошибка в главной странице в файле index.page.tsx 60 строка: Incompatible element override from component

Из-за того что у тебя не пойми что творится в [индекс](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/landing/fragments/landing-header/src/index.ts) файле. Зачем ты смначала экспортируешь HeaderBlock, а потом создаешь пустой класс с таким же названием и экспортируешь его же?

И начинай гуглить ошибки, или хотя бы в переводчик забивать, там же все написано: `Incompatible element override from component` говорит, что ты пытаешься перезаписать уже существующий HeaderBlock, как раз зачем-то создавая этот пустой класс

> И еще вопрос: как обнулять стили, к примеру для тега body? Нужно создавать файл css?

https://github.com/atls/orbitto/blob/master/ui/theme/src/global.styles.tsx

2022-09-07 11:01 UTC, eshevlyakova commented
@TFK70 
> говорит, что ты пытаешься перезаписать уже существующий HeaderBlock, как раз зачем-то создавая этот пустой класс

Эта ошибка была еще до создания класса, webstorm предложил его создать и я забыла удалить. Класс я удалила, ошибка осталось. Вообщем я где-то пересоздаю существующий блок?

2022-09-07 11:09 UTC, TFK70 commented
@eshevlyakova 

> Вообщем я где-то пересоздаю существующий блок?

Я думаю тебе самой это высказывание ни о чем не говорит. Гугли, смотри почему у людей эта ошибка обычно появляется, как её фиксят

> Эта ошибка была еще до создания класса, webstorm предложил его создать и я забыла удалить. Класс я удалила, ошибка осталось.

Не имеет значения. Плюс у меня этой ошибки нет, после того как я поправил все, о чём я тебе написал. Если ты сделала изменения и ошибка сохранилась - сделай коммит, приложи точный лог, я посмотрю

2022-09-07 14:02 UTC, eshevlyakova commented
@TFK70 
> https://github.com/atls/orbitto/blob/master/ui/theme/src/global.styles.tsx

А как подключить эти стили? Я взяла за пример этот репозиторий и единственное упоминание theme я нашла в app/package.json - https://github.com/torin-asakura/dream-team/blob/master/landing/app/package.json#L47
Себе также добавила эту зависимость, но к моей странице стили не применились

2022-09-07 14:06 UTC, TFK70 commented
@eshevlyakova Смотри внимательнее пожалуйста пример, ты можешь добавить хоть 100 новых зависимостей в свой проект и ничего не изменится, пока ты их не используешь

И это не единственное место где упоминается @ui/theme, ищи рекурсивным поиском по репе или пользуйся поиском гитхаба

2022-09-07 14:41 UTC, eshevlyakova commented
@TFK70 
Стили подключить получилось. 
Возвращаясь к ошибке `Incompatible element override from component`. В браузере ошибок нет, но webstorm подсвечивает красным. Вызов класса убрала. Пыталась гуглить, но не нашла ответ

2022-09-07 14:58 UTC, TFK70 commented
@eshevlyakova Ошибки в вебшторме не являются источником правды, если бы ты заполняла запрос о помощи по форме это бы не растянулось на несколько комментов

Чтобы вебшторм правильно анализировал код - тебе нужно перенести в корень проекта tsconfig, такой же как в примерах

2022-09-08 10:41 UTC, eshevlyakova commented
@TFK70 
Как исправить ошибки линта `Error: No matching configuration found for` или из-за чего они могли появиться?

2022-09-08 11:26 UTC, TFK70 commented
> @TFK70 Как исправить ошибки линта `Error: No matching configuration found for` или из-за чего они могли появиться?

Нужно использовать определенную версию еслинта, я кинул фикс

2022-09-08 13:02 UTC, eshevlyakova commented
@TFK70 
> Нужно использовать определенную версию еслинта

Теперь появилась данная ошибка:
` Typecheck
➤ YN0000: │   Error: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015',
➤ YN0000: │        'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext'.`
Гуглила, но не нашла решение

2022-09-08 13:09 UTC, TFK70 commented
> @TFK70
> 
> > Нужно использовать определенную версию еслинта
> 
> Теперь появилась данная ошибка: ` Typecheck ➤ YN0000: │ Error: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', ➤ YN0000: │ 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext'.` Гуглила, но не нашла решение

Тоже проблема с версией тайпскрипта, пофиксил

2022-09-08 13:27 UTC, eshevlyakova commented
@TFK70 
Теперь еще больше ошибок typecheck, и большая часть подобных:
` Error: Cannot find module 'react' or its corresponding type declarations.`

Это тоже из версий или уже мои ошибки?

2022-09-08 13:29 UTC, TFK70 commented
> @TFK70 Теперь еще больше ошибок typecheck, и большая часть подобных: ` Error: Cannot find module 'react' or its corresponding type declarations.`
> 
> Это тоже из версий или уже мои ошибки?

У меня ни одной такой ошибки нет

И теперь все ошибки из тайпчека существуют по делу - их надо исправлять

2022-09-08 13:38 UTC, eshevlyakova commented
@TFK70 
Может быть что у меня только локально эти ошибки?
И как вообще их исправлять? Если у меня установлено все и в package.json прописано. Да и до этого модули все находились

2022-09-08 13:41 UTC, TFK70 commented
@eshevlyakova 1. Убедись что ты сделала yarn
2. Убедись что запускаешь команду из корня
3. Убедись что в корне лежит корректный тсконфиг

2022-09-08 17:37 UTC, eshevlyakova commented
@TFK70 
Все работает, спасибо. Теперь все ошибки связаны с children, к примеру вот одна из них: ` Error: Property 'children' does not exist on type '{}'.`
Но они появляются в папках ui и globals, а я эти папки не трогала. Это из-за версии react (я в интернете нашла) или моя ошибка?

2022-09-08 17:37 UTC, TFK70 commented
@eshevlyakova У тебя есть понимание того, что такое children в реакте?

2022-09-08 17:39 UTC, eshevlyakova commented
@TFK70 
Это дочерние элементы, причем не обязательно какой-то компонент, это может быть просто текст

2022-09-08 17:42 UTC, TFK70 commented
@eshevlyakova в общем, с 18 версии реакта children отсутствуют в дефолтном наборе пропов в типе FC, для того чтобы включить children в набор типизированных пропов у компонента нужно использовать тип `PropsWithChildren<Props>`

То есть, если у тебя компонент типизирован как FC, то твоя типизация будет выглядеть так: `PropsWithChildren<FC>`

2022-09-09 08:24 UTC, eshevlyakova commented
@TFK70 
А такого рода ошибки, как решать: `  Error: Type '{ children: any[]; divider: number; }' is not assignable to type 'IntrinsicAttributes & DividerProps'.
➤ YN0000: │          Property 'children' does not exist on type 'IntrinsicAttributes & DividerProps'.`

Я нашла в интернете только , что они также возникают после 18 версии react из-за того что компонент пытается получить доступ к children

2022-09-09 08:25 UTC, TFK70 commented
@eshevlyakova просто почитай внимательнее мой коммент и сообщение об ошибке: `Property 'children' does not exist on type 'IntrinsicAttributes & DividerProps`

2022-09-09 08:35 UTC, eshevlyakova commented
@TFK70 
Ошибка решается также, я пробывала к примеру этот код: `export const Button: FC<ButtonProps>`, заменить на: `export const Button: PropsWithChildren<ButtonProps>`
Ошибка осталась

2022-09-09 08:54 UTC, TFK70 commented
@eshevlyakova а зачем ты пытаешься пофиксить эту ошибку в Button когда проблема в Content?

Чтобы не было проблем с AnimatePresence тебе нужно обновить framer-motion до последней версии, но я вообще не понимаю зачем тебе фреймер и остальная куча компонентов в ui которые ты не собираешься использовать

2022-09-09 16:14 UTC, TFK70 requested changes

2022-09-09 16:14 UTC, TFK70 commented on globals/data/package.json
> +  "name": "@globals/data",
Зачем тебе `@globals/data`?

2022-09-09 16:14 UTC, TFK70 commented on globals/data/src/helpers/get-client.helper.ts
> +    uri: 'https://wp.misik.pro/graphql',
У тебя проект называется misik.pro? И у тебя уже есть какой-то бэкенд?

2022-09-09 16:14 UTC, TFK70 commented on landing/app/src/.next/server/webpack-runtime.js
> +/*
Это бандл, это должно быть в .gitignore

2022-09-09 16:14 UTC, TFK70 commented on landing/app/src/pages/_app.tsx
> +    <ApolloProvider client={client}>
У тебя не используется apollo

2022-09-09 16:14 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +  const StyledHeader = styled.header`
Наш стек ориентирован на то, чтобы не писать css во фрагментах. Фрагмент - это абстрактный компонент твоего frontend приложения, ориентированный на имплементацию какой-то определенной **бизнес** логики. Описание стилей - не бизнес логика, этим занимается слой ui

Здесь ты не использовала почти ни одного компонента из ui и код даже приблизительно не соответствует нашим стандартам

2022-09-12 15:37 UTC, eshevlyakova commented
@TFK70 
> Здесь ты не использовала почти ни одного компонента из ui 

1. Получается вместо своего container я могу использовать Layout, задав ему нужную ширину?
2. Не могу понять куда переносить стили в style или design?

2022-09-12 16:30 UTC, TFK70 commented
@eshevlyakova 

> Получается вместо своего container я могу использовать Layout, задав ему нужную ширину?

Смотри по ситуации. Layout - это базовый компонент. Посмотри внимательнее где и для чего он используется. Свои компоненты ты тоже можешь создать, но:

1. Когда это действительно необходимо (когда компоненту нужно накидать много стилей, например)
2. Использовать базу из `@ui/layout`

> Не могу понять куда переносить стили в style или design?

1. Я не понял что за design
2. Ответы на все вопросы которые ты задаешь есть в примерах, тебе нужно просто сделать по аналогии

2022-09-12 17:08 UTC, eshevlyakova commented
@TFK70 
Кажется поняла. Есть ли мне подходит готовый компонент из ui, то я использую его и стилизую в той же папке, а если нужно все таки создать свой компонент, то делаю как сейчас в моем проекте
Правильно?

2022-09-12 17:09 UTC, TFK70 commented
@eshevlyakova ничего не понял

2022-09-12 17:18 UTC, eshevlyakova commented
@TFK70 
К примеру мне нужно сделать кнопку. Если в uikit есть подходящий мне компонент, то я использую его (а не создаю свой, как сейчас) и стили пишу в папке ui
А если у меня какая-то кастомная кнопка и мне не подходит готовый шаблон, то я создаю компонент и пишу стили, как сейчас все сделала:
```tsx
  const CustomButton = styled.button"
    background-color: #616161;
    padding: 35px 40px; "
```

2022-09-12 17:21 UTC, TFK70 commented
@eshevlyakova нет, стили как у тебя сейчас ты нигде и никогда не пишешь, покажи хоть одно место где мы делаем так же на одном из примеров

> К примеру мне нужно сделать кнопку. Если в uikit есть подходящий мне компонент, то я использую его (а не создаю свой, как сейчас) и стили пишу в папке ui

Я тоже не понимаю к чему вопрос. Если ты не понимаешь что находится в `@ui/button` - так и следует задать вопрос, потому что ты как будто специально игнорируешь код который я тебе отправил для ознакомления

И да, uikit для того и создан, чтобы не писать каждый раз одни и те же компоненты с нуля

2022-09-12 17:25 UTC, eshevlyakova commented
@TFK70 
> нет, стили как у тебя сейчас ты нигде и никогда не пишешь

Я не понимаю тогда откуда появляются стили, у кастомных компонентов (не из uikit)?

> Если ты не понимаешь что находится в @ui/button

Да, вроде все понятно. Сам компонент button и стили для него

2022-09-12 17:39 UTC, TFK70 commented
@eshevlyakova 

> Я не понимаю тогда откуда появляются стили, у кастомных компонентов (не из uikit)?

[пишутся в инлайне](https://github.com/torin-asakura/VSBLE/blob/master/site/fragments/creators/src/card/card.component.tsx#L50)

[Создаются через фабрики](https://github.com/torin-asakura/VSBLE/blob/master/ui/checkbox/src/checkbox.styles.ts#L33), потом прокидываются в [styled](https://github.com/torin-asakura/VSBLE/blob/master/ui/checkbox/src/checkbox.component.tsx#L28)

[Пишутся в styled напрямую](https://github.com/atls/uikit/blob/master/ui-proto/popover/src/popover.stories.tsx#L16)

2022-09-14 14:44 UTC, eshevlyakova commented
@TFK70 
> Зачем тебе @globals/data?

`Error: @globals/data@workspace:0.0.1: Workspace not found (@globals/data@workspace:0.0.1)`
Хотя я вроде его нигде не использую и не вызываю

2022-09-14 14:48 UTC, TFK70 commented
@eshevlyakova и поэтому вместо того, чтобы разобраться что это за ошибка, ты решила оставить половину кода от другого проекта который даже не используешь?)

Погугли ошибку и больше не делай так пожалуйста, это безответственный и неэффективный подход, у тебя так не выйдет чему-то обучиться

2022-09-14 15:47 UTC, eshevlyakova commented
@TFK70 
> Погугли ошибку

Эта ошибка происходит из-за того, что зависимость не может быть разрешена в существующую область, но я не нашла как ее исправить

2022-09-14 15:48 UTC, TFK70 commented
@eshevlyakova что значит "зависимость не может быть разрешена в существующую область"?

2022-09-14 15:52 UTC, eshevlyakova commented
@TFK70 
A dependency uses a workspace: range that cannot be resolved to an existing workspace.

Сейчас перевела через другой переводчик и получается что зависимость использует рабочую область, диапазон которой не может быть разрешен для существующей рабочей области.

2022-09-14 15:55 UTC, TFK70 commented
@eshevlyakova ладно, что значит "зависимость использует рабочую область, диапазон которой не может быть разрешен для существующей рабочей области"?

Я не прошу тебя забить за меня лог об ошибке в переводчик. Я прошу чтобы ты объяснила как ты понимаешь эту ошибку, если вообще понимаешь. Потому что [это](https://github.com/atls-academy/eshevlyakova.github.io/pull/11#issuecomment-1246965759) сообщение было сформулировано так, будто ты всё поняла и приняла осознанное решение

2022-09-14 16:01 UTC, eshevlyakova commented
@TFK70 
> ладно, что значит "зависимость использует рабочую область, диапазон которой не может быть разрешен для существующей рабочей области"?

Я не очень понимаю что такой range

2022-09-15 15:53 UTC, eshevlyakova commented
@TFK70 
А как можно добавить стили для всех компонентам Layout? Просто мне кажется писать в инлайне повторяющийся стили плохая идея

2022-09-20 13:03 UTC, TFK70 commented
@eshevlyakova Почему это? Как ты без пикселей верстать хочешь?

2022-09-20 14:38 UTC, eshevlyakova commented
@TFK70 
Тогда немного не понимаю, как можно делать адаптив с px при таких breakpoints:
min-width: 64em
min-width: 52em
min-width: 40em
Получается что для экрана в 1100px и 2560px действует одна ширина к примеру 1060px и на экране 2560px слишком много свободного места

2022-09-21 14:09 UTC, eshevlyakova commented
@TFK70 
Ты ранее писал про то, что стили можно писать в [инлайне](https://github.com/torin-asakura/VSBLE/blob/master/site/fragments/creators/src/card/card.component.tsx#L50)
А как в инлайне указывать единицу измерения, когда я пишу стили для разных разрешений? К примеру мне нужна единица vh, но если я напишу так: `height={[40 ,50 ,70 ,90]}` то ставятся px

2022-09-21 14:16 UTC, TFK70 commented
@eshevlyakova height={[70, ‘70vh’…]}

2022-09-21 16:19 UTC, eshevlyakova commented
@TFK70 
К компоненту Text из uikit я хочу подключить свой шрифт. Я так поняла его нужна прописать здесь, но что означают [цифры после названия шрифтов](https://github.com/torin-asakura/dream-team/blob/14f339057d77b2e630a503cf9f179b7b213625c1/ui/theme/src/theme/fontSizes.ts#L2)?

2022-09-21 16:22 UTC, TFK70 commented
@eshevlyakova Файл называется fontSizes, а цифры - это размеры текста в пикселях

2022-09-21 16:29 UTC, eshevlyakova commented
@TFK70 
Тогда шрифты подключаются с помощью [этого файла](https://github.com/torin-asakura/dream-team/blob/14f339057d77b2e630a503cf9f179b7b213625c1/ui/theme/src/theme/fonts.ts)?
Если да, то не могу куда вставлять @import шрифтов (`@import url('http://fonts.cdnfonts.com/css/helvetica-2');`)?

2022-09-21 16:43 UTC, TFK70 commented
@eshevlyakova вот почему нельзя было просто сформулировать свою проблему и задать вопрос?) "Мне нужен кастомный шрифт, как мне его подключить?"
Зачем тратить время на эти угадывания?

Импорт в глобальных стилях - https://github.com/torin-asakura/dream-team/blob/master/ui/theme/src/global.styles.tsx#L16

2022-09-23 13:43 UTC, eshevlyakova commented
@TFK70 
А как в инлайне писать стили для обычных тегов? К примеру для div, я хочу прописать `<div backgroundColor="green">text</div>`

2022-09-23 13:52 UTC, TFK70 commented
@eshevlyakova никак, они не имеют никакого отношения к emotion

2022-09-23 13:53 UTC, TFK70 commented
@eshevlyakova И мы никогда не используем в вёрстке дефолтные html тэги, для этого и есть компоненты из layout

2022-09-23 13:55 UTC, eshevlyakova commented
@TFK70 

1. То есть я должна использовать только компоненты из uikit?
2. Я правильно поняла, что аналог div это Box?

2022-09-23 13:57 UTC, TFK70 commented
@eshevlyakova 1. Да
2. Box это и есть div, посмотри в uikit https://github.com/atls/uikit/blob/master/ui-parts/layout/src/box/box.component.ts

2022-09-25 16:13 UTC, eshevlyakova commented
@TFK70 
А как задать свой border-radius кнопкам(к примеру [этой](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/landing/fragments/landing-section-banner/src/banner.component.tsx#L85-L92))? 
По умолчанию у всех кнопок стоит `border-radius: 40px`. Если я пишу в инлайне, то свойство не отображается в браузере

2022-09-25 16:20 UTC, TFK70 commented
@eshevlyakova а почему они должны применяться через инлайн?

2022-09-25 16:24 UTC, eshevlyakova commented
@TFK70 
> а почему они должны применяться через инлайн?

Если честно незнаю, просто попробовала через инлайн - не получилось. И я не могу найти где задано `border-radius: 40px`

2022-09-26 14:27 UTC, eshevlyakova commented
@eshevlyakova @TFK70 подскажешь с этим?

2022-09-26 14:27 UTC, TFK70 commented
@eshevlyakova я не вижу вопроса

2022-09-26 14:28 UTC, eshevlyakova commented
@TFK70 
Как задать свой border-radius кнопкам(к примеру [этой](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/landing/fragments/landing-section-banner/src/banner.component.tsx#L85-L92))?

2022-09-26 14:29 UTC, TFK70 commented
@eshevlyakova через .styles файлы внутри ui/button, тебе нужен shape styles

2022-09-26 16:15 UTC, eshevlyakova commented
@TFK70 И еще вопрос: где для Button задаются padding (в браузере отображается `padding-left: 22px;  padding-right: 22px;`, но я не могу найти откуда они прописываются)?

2022-09-26 16:19 UTC, TFK70 commented
@eshevlyakova там же, в файлах .styles в ui/button

2022-09-26 16:30 UTC, eshevlyakova commented
@TFK70 я смотрела, но не поняла где именно. Вроде нигде не прописывается. Эти padding прописываются в styles/base?

2022-10-03 07:58 UTC, eshevlyakova commented
@TFK70 
А как поставить для кнопок `<Button  size='rounded'>` вертикальные падинги? 
Потому что как я поняла в [ui](https://github.com/atls/uikit/blob/master/ui-parts/button/src/shape/shape.styles.ts#L60-L61) в функции createShapeStyles можно указывать только paddingLeft и paddingRight
Локально этой функции [у меня нет](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/ui/button/src/styles/shape/abstract/rounded-size.styles.ts#L1), я ее импортирую

2022-10-03 08:07 UTC, TFK70 commented
@eshevlyakova а зачем они? У тебя есть size (он же height) в пикселях

2022-10-03 08:10 UTC, eshevlyakova commented
@TFK70 
Уже поняла, что не нужны. Я просто хотела ограничить высоту для данной иконки:
<img width="202" alt="Снимок экрана 2022-10-03 в 11 09 53" src="https://user-images.githubusercontent.com/79781486/193530056-83e122dd-4d3e-4948-9f92-ad6f631e47f2.png">
С помощью вертикальных падингов, но сейчас увидела что в других примерах просто внутрь <Button> добавляют <Layout>

2022-10-03 09:51 UTC, eshevlyakova commented
@TFK70 
А эта ошибка также из-за версии или это уже баг в моем коде?
`Error: Type '{ children: ReactNode; divider: number; }' is not assignable to type 'IntrinsicAttributes & DividerProps'.`

<img width="668" alt="Снимок экрана 2022-10-03 в 12 37 24" src="https://user-images.githubusercontent.com/79781486/193546536-79a15274-aa49-49db-b1b2-d6f0171003b7.png">

Я гуглила эту ошибку, но не особо поняла как ее исправить. Файл ui/button/src/button.component.tsx брала [отсюда](https://github.com/torin-asakura/dream-team/blob/master/ui/button/src/button.component.tsx)

2022-10-03 09:51 UTC, TFK70 commented
@eshevlyakova баг в коде

2022-10-03 10:47 UTC, eshevlyakova commented
@TFK70 
> Error: Type '{ children: ReactNode; divider: number; }' is not assignable to type 'IntrinsicAttributes & DividerProps'.

А как эту ошибку исправить, из-за чего она вообще возникает?

2022-10-03 10:50 UTC, TFK70 commented
@eshevlyakova когда тип А не соответствует типу B

2022-10-03 11:15 UTC, eshevlyakova commented
@TFK70 
Получается divider: number не соответсвует типу 'IntrinsicAttributes & DividerProps'?
Я когда гуглила, читала про то, что нужно к DividerProps добавить children. Сейчас получается в [DividerProps](https://github.com/atls/uikit/blob/master/ui-parts/button/src/content/content.interfaces.ts) прописано свойство divider, но нигде не написано что его можно использовать как атрибут, так?

2022-10-03 13:45 UTC, eshevlyakova commented
@TFK70 
И еще вопрос можно ли в [таком файле](https://github.com/torin-asakura/dream-team/blob/master/fragments/landing-work-directions/src/messages.ts) написать тег <br> и чтобы он сработал?

2022-10-03 13:49 UTC, TFK70 commented
@eshevlyakova 

> Получается divider: number не соответсвует типу 'IntrinsicAttributes & DividerProps'?

{ children: ReactNode; divider: number; } не соответствует типу IntrinsicAttributes & DividerProps

> Сейчас получается в [DividerProps](https://github.com/atls/uikit/blob/master/ui-parts/button/src/content/content.interfaces.ts) прописано свойство divider, но нигде не написано что его можно использовать как атрибут, так?

Ничего не понял

> И еще вопрос можно ли в [таком файле](https://github.com/torin-asakura/dream-team/blob/master/fragments/landing-work-directions/src/messages.ts) написать тег <br> и чтобы он сработал?

Ни в коем случае, это файл отвечающий за контент

1. `<br>` - это не контент, а вёрстка
2. Зачем тебе `<br>`? Для вертикальных отступов используй layout с flexBasis
3. Повторюсь, что HTML нигде использовать нельзя, кроме ui

2022-10-03 13:53 UTC, eshevlyakova commented
@TFK70 
> Зачем тебе <br>? Для вертикальных отступов используй layout с flexBasis

Для того, чтобы сделать перенос в предложении:
```html
Обучаем <br />
профессионалов <br />
для революции в IT
```
Тогда с помощью ширины ограничивать?

2022-10-03 13:55 UTC, TFK70 commented
@eshevlyakova В твоем случае это можно сделать разделив контент по словам
Сделай split и рассортируй каждое слово по строчкам

2022-10-03 13:58 UTC, eshevlyakova commented
@TFK70 
Файл messages.ts:
```typescript
export const messages = {
    oneLineTitle: 'Обучаем',
    secondLineTitle: 'профессионалов',
    thirdLineTitle: 'для революции в IT',
  }
```
Вот так?

2022-10-03 13:59 UTC, TFK70 commented
@eshevlyakova можно и так

2022-10-03 16:04 UTC, eshevlyakova commented
@TFK70 
> { children: ReactNode; divider: number; } не соответствует типу IntrinsicAttributes & DividerProps

Я никак не могу понять почему это не соответствует и как это исправить. Единственное пока понятное решение, которое я нагуглила это, что нужно добавить children к [этому](https://github.com/atls/uikit/blob/master/ui-parts/button/src/content/content.interfaces.ts#L1)
Но в примере вроде так не делают, да и DividerProps находится не локально

2022-10-03 16:09 UTC, TFK70 commented
@eshevlyakova а тебе зачем чилдрен в дивайдере? Ты используешь уже типизированный компонент, и он говорит что ты его используешь неверно

2022-10-03 16:31 UTC, eshevlyakova commented
@TFK70 
> Ты используешь уже типизированный компонент, и он говорит что ты его используешь неверно

Я скопировала этот ui компонент из примера, почему он там работает, а у меня нет?
Нужно искать ошибки в этом файле или в другом?

2022-10-03 16:53 UTC, TFK70 commented
@eshevlyakova для начала сделай yarn upgrade-interactive и обнови все @atls пакеты до последней версии

2022-10-03 17:08 UTC, eshevlyakova commented
@TFK70 
После обновления все заработало. В следующий раз вначале буду запускать yarn upgrade-interactive)

2022-10-03 17:23 UTC, TFK70 commented
@eshevlyakova нене нен надо
Бери ровно те зависимости, которые актуальны на наших последних проектах, обновлять абсолютно все до  лейтеста (за исключением, разве что, наших @atls либ) не надо

2022-10-03 17:36 UTC, eshevlyakova commented
@TFK70 Я имела ввиду при подобной ошибке и обновлять буду только @atls пакеты

2022-10-04 08:33 UTC, eshevlyakova commented
@TFK70 
А нужно ли мне также создавать для каждого компонента (в папке fragments) файл name.interface.ts?
Просто в [примерах](https://github.com/torin-asakura/dream-team/tree/master/fragments/navigation/src) в папке каждого компонента есть такой файл, но у меня и нет мультиязычности

2022-10-04 08:37 UTC, TFK70 commented
@eshevlyakova Создавай тогда, когда они нужны - все просто

2022-10-04 11:13 UTC, eshevlyakova commented
@TFK70 
После обновления, всем картинкам (компонент из ui <Image>) задается margin-left: 12px

<img width="619" alt="Снимок экрана 2022-10-04 в 14 09 23" src="https://user-images.githubusercontent.com/79781486/193804106-e384df9e-20ab-4569-af80-98f08bc38d40.png">

В компоненте ui/image данный отступ не задается. Как исправить это?

2022-10-04 11:30 UTC, TFK70 commented
@eshevlyakova я без понятия, по умолчанию у имейджа никаких маржинов нет

Начинай тоже уже дебажить, найти в каком месте компоненту задаётся маржин - не такая трудная задача

2022-10-04 13:50 UTC, TFK70 requested changes

2022-10-04 13:50 UTC, TFK70 commented on .gitignore
> +landing/app/src/.next/server/webpack-runtime.js
Положи в игнор всю директорию .next

2022-10-04 13:50 UTC, TFK70 commented on landing/app/src/.next/server/webpack-runtime.js
> +/*
?

2022-10-04 13:50 UTC, TFK70 commented on landing/app/src/.next/static/webpack/ae869608cc05eedf.webpack.hot-update.json
> +{"c":["pages/index","webpack"],"r":[],"m":[]}
Это все нужно убрать из гита и добавить в игнор

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    backgroundColor='#616161'
Цвет должен браться из темы

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    padding={['20px 5px', '22px 5px', '25px 5px', '30px 5px']}
Мы не используем паддинги
Вместо этого - `<Layout flexBasis={..} />`

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='100%' maxWidth={[600, 790, 1000, 2500]} margin='0 auto' />
Margin тоже не используем

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    color='#FFFFFF'
Все цвета из темы должны браться

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    justifyContent={['end', 'end', 'start', 'start']}
Достаточно 3 брейкпоинтов: end, end, start
мобилка, таблет, десктоп

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          lineHeight={['110%', '110%', '110%', '120%']}
Это берется из темы

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          fontSize={[80, 70, 76, 96]}
И это из темы

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          fontWeight='400'
И это из темы

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          {messages.oneLineTitle} <br />
html в верстке не используем, тем более `<br>`, вместо которого я говорил тебе использовать отступ через лейаут флекс базис

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          {messages.thirdLineTitle}&nbsp;
`&nbsp` - если это какой-то закодированный символ, то он должен находиться в `@ui/text` и иметь соответствующее название

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +            {' '}
Так не делаем
В `@ui/text` есть компонент `<Space />`, используй его для строчных пробелов

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +import { messages }    from './messages'
Нет, ты же видела что мы не так используем месседжи

Объект интла должен обязательно браться из общего контекста, из `<IntlProvider />`, для этого существует хук `useIntl()`, но на последних проектах (VSBLE, например) мы используем компонент `<FormattedMessage />` так как он выглядит чище

Примеров всего этого - куча

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    paddingBottom={['65px', '65px', '38px', '48px']}
Не буду под каждым местом комментарий дублировать, просто имей ввиду что паддинги с маржинами нужно убрать ото всюду

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              alt='Иконка компьютерной мышки'
Этот текст тоже должен находиться в intl

2022-10-04 13:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/messages.ts
> +  oneLineTitle: 'Обучаем',
А, я понял, месседжи тоже не регистрируются в intl. Плохо, надо переделать, следуй примерам на проектах

Делай так же как на VSBLE: все месседжи храни [здесь](https://github.com/torin-asakura/VSBLE/blob/master/site/entrypoints/renderer/locales/en.json), в точке входа в формате JSON

2022-10-04 13:50 UTC, TFK70 commented on landing/pages/index-page/src/index.page.tsx
> +  <main>
Никакого HTML за пределами ui

2022-10-04 13:50 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        .mapboxgl-ctrl-group button {
У тебя в приложении нигде нет mapbox, убери эти стили, они не нужны

2022-10-04 13:50 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        blockquote,
По-моему тут многовато тегов

2022-10-04 13:50 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        img {
Ни в коем случае так не делай
Стили для имейджа задавай в `@ui/image`

2022-10-04 13:50 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        .swiper-work-directions {
Свайпера у тебя тоже нет, тоже убирай

2022-10-04 13:50 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        @keyframes draw {
И анимация эта у тебя нигде не используется, тоже убери

2022-10-05 11:43 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              alt='Иконка компьютерной мышки'
А как прописать текст в alt? Просто в [этом проекте](https://github.com/torin-asakura/VSBLE) у картинок он вообще не задан. А в других примерах используется другой способ вывода текста
Если я пишу так: 
`alt={<FormattedMessage id='altComputerMouse' defaultMessage='Иконка компьютерной мыши' />}`
То в браузере отображается так: `alt="[object Object]"`

2022-10-05 11:45 UTC, eshevlyakova commented
@TFK70 
> Этот текст тоже должен находиться в intl

А как прописать текст в alt? Просто в [этом проекте](https://github.com/torin-asakura/VSBLE) у картинок он вообще не задан. А в других примерах используется другой способ вывода текста
Если я пишу так:
alt={<FormattedMessage id='altComputerMouse' defaultMessage='Иконка компьютерной мыши' />}
То в браузере отображается так: alt="[object Object]"

2022-10-05 12:37 UTC, TFK70 commented
@eshevlyakova то есть то, что ты пытаешься засунуть компонент в проп, который принимает string - тебя не смущает?

Я уже писал что ты можешь использовать `useIntl()` чтобы получить объект интла из контекста, посмотри примеры на misik, например

2022-10-06 08:46 UTC, TFK70 commented
@eshevlyakova https://github.com/torin-asakura/VSBLE/blob/c58a670a8478316115ace786b6e07f2eb8681ab5/site/fragments/settings/src/delete-account/delete-account.component.tsx#L15

2022-10-06 09:41 UTC, TFK70 commented
@eshevlyakova погугли, зачем меня каждый раз о новой ошибке спрашивать?

2022-10-06 11:00 UTC, eshevlyakova commented
@TFK70 Потому что не получается нагуглить. Единственное решение которое я поняла: обновить версию typescript. Но это не сработало

2022-10-06 11:02 UTC, TFK70 commented
@eshevlyakova 
Тогда сделай коммит, приложи логи и скажи как воспроизвести
Я не понимаю к чему вопросы по типу

> Она означает, что я в каком-то из файлов хочу импортировать Locale, которого нет в Intl?

Зачем снова надо было растягивать 1 вопрос на 4 комментария, который еще и остался без ответа?

2022-10-06 11:23 UTC, TFK70 commented
@eshevlyakova нужно [зафиксировать](https://github.com/atls-academy/eshevlyakova.github.io/pull/11/commits/91b6d92e9d2dcf98ed29ba9c1267a3788e6bc29a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19) `react-intl` на версии `5.24.3`

2022-10-06 13:34 UTC, TFK70 commented on landing/entrypoints/renderer/locales/en.json
> +    "banner.oneLineTitle": "Обучаем",
Файл называется `en.json`, но локаль у тебя ru

2022-10-06 13:37 UTC, TFK70 commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default} from '@landing/index-page'
Что с форматированием? husky сломался?

2022-10-06 13:42 UTC, TFK70 commented on landing/fragments/landing-section-banner/package.json
> +        "typescript": "^4.8.4"
Это тоже плюсом: кривые peerDependencies и typescript, который не нужен

В следующие разы не буду дублировать, знай что это надо будет везде поправить

2022-10-06 13:43 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      height={['89vh', '89vh', '90vh']}
Мы не используем никаких `vh`, только пиксели

2022-10-06 13:44 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
Просто всегда задавай размеры в пикселях, как в дизайне, во всём этом нет необходимости

2022-10-06 13:45 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +            letterSpacing='-0.02em'
letterSpacing можешь убрать ото всюду

2022-10-06 13:46 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +            borderTop='1px solid rgba(255, 255, 255, 0.25)'
border тоже берется из темы

2022-10-06 13:49 UTC, TFK70 commented on ui/image/src/image.component.ts
> +const Image = styled.img<ImageProps>(baseStyles, absoluteStyles, { pointerEvents: 'none' })
А, погоди, а почему у тебя здесь image саморучно собранный?

Он [берётся](https://github.com/torin-asakura/VSBLE/blob/master/ui/image/src/index.ts) из `@atls-ui-parts/image`

Вообще ориентируйся преимущественно на VSBLE и на [orbitto](https://github.com/atls/orbitto), это одни из наших последних проектов, там используются наши последние практики, следуй им

2022-10-06 13:51 UTC, TFK70 commented on ui/social-links/src/social-links.component.tsx
> +                  id: 'altIconGithub',
Посмотри внимательнее на то, как мы даём idшники месседжам, у тебя формат для них абсолютно другой

2022-10-06 13:53 UTC, TFK70 commented on ui/social-links/src/social-links.component.tsx
> +                src='http://dev.eshevlyakova.ru/svg-atlantis/github.svg'
`.jpg` и прочий растр ещё ладно - в целом можешь грузить его пока как хочешь, но свг ты должна хранить в `@ui/icons` как [тут](https://github.com/atls/orbitto/tree/master/ui/icons). Делаешь `yarn workspace @ui/icons build` и  твои `.svg` превращаются в `.tsx`

2022-10-06 13:53 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        dl,
А что с тегами-то? Убери лишнее

2022-10-06 13:54 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +          font-family: "primary", sans-serif;
Убери, `font-family` не так задаётся, у тебя `emotion` и тема на это есть

2022-10-06 16:22 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
@TFK70 
Я бы все таки оставила так, потому что в дизайне указана высота 1080px, но например на маке 13 дюймов это выглядит так:
<img width="1279" alt="Снимок экрана 2022-10-06 в 19 15 41" src="https://user-images.githubusercontent.com/79781486/194365223-318ad23e-39bb-4023-943f-1c7b7bd273b6.png">

Если сделать меньше, то на разрешении 2560px это будет выглядеть некорректно. Можно оставить так, как есть?

2022-10-06 16:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
Тогда почему у тебя такие странные значения в `vh`? Почему не использовать %?

2022-10-06 17:12 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
Потому что проценты будут считать от родителя, и ничего не будет работать. Вот со значением 90%:
<img width="829" alt="Снимок экрана 2022-10-06 в 20 09 10" src="https://user-images.githubusercontent.com/79781486/194375875-6940a900-3e36-4d0c-ac18-073e5ce3b160.png">
А vh рассчитывает от высоты устройства, вне зависимости от родителя. Насчет самих значений, не поставила 100vh потому что сверху еще шапка

2022-10-06 17:13 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Это просто контейнер, который ограничивает ширину контента. Поставила 98% и выровняла по центру чтобы текст не прилипал к краям

2022-10-06 17:16 UTC, eshevlyakova commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default} from '@landing/index-page'
Я сейчас работаю в vsc (пока не нашла плагин чтобы автоматически в export/import отступы ставились). У меня же пробная версия закончилась, пиратки я не особо люблю. И я пару дней назад отправила заявку на бесплатное получение продуктов jetbrains, так как я в школе учусь. Пока жду ответ

2022-10-06 18:02 UTC, TFK70 commented on landing/entrypoints/renderer/src/pages/index.ts
> +export { default} from '@landing/index-page'
1. Причём тут IDE? husky никакого отношения к IDE не имеет: ты делаешь коммит - у тебя срабатывает хук который запускает format
2. Это объясняет почему у тебя в некоторых файлах нет new line в конце файлов

2022-10-06 18:16 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
> Дай на него ссылку в дизайне

2022-10-07 09:35 UTC, eshevlyakova commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +  <IntlProvider messages={{}} locale='ru' defaultLocale='ru'>
А есть какой-то пример? Просто в [VSBLE](https://github.com/torin-asakura/VSBLE/blob/master/site/entrypoints/renderer/src/pages/_app.tsx#L7) также пустой messages

2022-10-07 09:41 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Его нет в дизайне. Тогда убрать этот элемент, а горизонтальные отступы сделать с помощью flexBasis (я видела так в VSBLE делали)?

2022-10-07 09:51 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Как нет в дизайне? Я не понимаю, ты же по дизайну верстку делаешь - как его может не быть в дизайне? Откуда он взялся тогда?

2022-10-07 09:52 UTC, TFK70 commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +  <IntlProvider messages={{}} locale='ru' defaultLocale='ru'>
Просто импортируй все месседжи из того жсона и засунь в этот проп, зачем тут пример?

2022-10-07 09:56 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Я когда верстала просто на html, css всегда делала div с классом container, который просто ограничивает ширину контента. В данном случае в дизайне этого блока нет

2022-10-07 09:59 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      height={['89vh', '89vh', '90vh']}
Я правильно поняла, что могу оставить [эту строчку](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-1/landing/fragments/landing-section-banner/src/banner.component.tsx#L18)?

2022-10-07 10:09 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Мне нужен не этот блок в дизайне, а место которое ты верстала в дизайне
Ты верстаешь по дизайну, ты приняла такое решение для верстки, скинь мне ссылку на дизайн, чтобы я мог посмотреть почему ты так сделала
Я вообще не понимаю в чем проблема, мне просто нужна ссылка на это место в дизайне, дай мне ссылку в следующем комменте

2022-10-07 10:14 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
А, прости. Неправильно поняла, я думала тебе как раз таки нужна ссылка на этот блок в дизайне.
https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2%3A1082

2022-10-07 10:17 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
1. Почему нельзя было просто выставить width в пикселях из дизайна
2. Отступы по краям делаются не так. Отступы по краям - это тоже пиксели, их нужно делать с помощью layout flexBasis, так что переделай

2022-10-07 10:36 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Выставляй все пиксели по дизайну

2022-10-07 10:54 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
@TFK70 
Мы наверно опять не так друг друга поняли) Я говорю про [этот блок](https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2%3A1082): если я задам ему ширину 1920px (как в дизайне), то с 900px по 1920px верстка просто сломается
А для других элементов (к примеру лого) я задаю размер по дизайну

2022-10-07 11:02 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Как она сломается? Покажи скриншот

2022-10-07 11:06 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Хотя я кажется понял о чём ты говоришь

Тогда да, оставь пожалуй так, но для хедера выстави maxWidth 1920px

Контентная часть будет иметь ширину 1200px, там таких проблем не будет, здесь просто хедер получается немного больше

2022-10-07 11:06 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Поставила width='1920px', как в дизайне:
<img width="829" alt="Снимок экрана 2022-10-07 в 14 05 43" src="https://user-images.githubusercontent.com/79781486/194539298-4975b7fc-3e67-4670-947d-559ee2ee3df6.png">

Просто дизайн сделан для больших экранов, а если задавать в процентах то ничего не ломается и выглядит адекватно и на больших разрешениях и на маленьких

2022-10-07 11:07 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Я использую тогда проценты?

2022-10-07 11:07 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Да, понял, оставь как сейчас есть тогда с учётом правок

2022-10-07 11:14 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
> Тогда да, оставь пожалуй так, но для хедера выстави maxWidth 1920px
Контентная часть будет иметь ширину 1200px, там таких проблем не будет, здесь просто хедер получается немного больше

Я смотрела другие шаги дизайна и сделала бы немного по другому. Так как брекпоинт срабатывает на 900px, то и с 1200px возникнут проблемы (экран 900px, а контент на 1200px). То я бы для контента сделала: width='100%' (на промежутке от 900px до 1200px все будет корректно работать) и maxWidth: '1200px' (начиная с 1300px страница будет выглядеть как в дизайне, а именно шапка больше контентной части). Хорошо?

2022-10-07 11:23 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Вот так на маленьком экране:
<img width="829" alt="Снимок экрана 2022-10-07 в 14 22 34" src="https://user-images.githubusercontent.com/79781486/194541967-809134ca-6977-4565-9117-1cbf54f5d8f9.png">
А так на большом (как в дизайне):
<img width="829" alt="Снимок экрана 2022-10-07 в 14 23 03" src="https://user-images.githubusercontent.com/79781486/194542031-05b262d3-73c3-4414-a92c-d92f91510600.png">

2022-10-07 11:50 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +    <Box width='98%' maxWidth={[600, 790, 2500]}>
Окей, можешь пока так оставить

2022-10-07 17:26 UTC, TFK70 requested changes

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +      <Box width='98%' maxWidth={[600, 790, 1920]}>
98% убери

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      width='98%'
тоже

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    flexDirection='column'
Используй Column

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    height={['89vh', '89vh', '90vh']}
На десктопе и мобилках разница в 1vh. С чем это связано? Почему 90vh на мобилках не подходит?

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      flexDirection='column'
Column

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      <Box display={['none', 'none', 'flex']} flexDirection='column' justifyContent='end'>
Column

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              fontFeatureSettings="'salt' on"
Не понимаю: это зачем?

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              fontFeatureSettings="'salt' on"
И я не думаю что styled-system понимает этот проп

2022-10-07 17:26 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Divider weight={1} backgroundColor='background.transparentGray' />
У дивайдера weight по умолчанию 1, так что можно не прописывать

2022-10-07 17:26 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        p {
Так ты будешь с тегами что-то делать? Третий раз ведь уже прошу

2022-10-07 18:05 UTC, eshevlyakova commented on landing/fragments/landing-header/src/header.component.tsx
> +      <Box width='98%' maxWidth={[600, 790, 1920]}>
Тогда сделать отступы с помощью layout flexBasis?

2022-10-07 18:07 UTC, eshevlyakova commented on ui/theme/src/global.styles.tsx
> +        p {
Нужно вообще убрать данные стили или оставить только для body и p?

2022-10-07 18:15 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +    height={['89vh', '89vh', '90vh']}
Оставила для всех 90vh, не было необходимости добавлять 89vh на других разрешениях

2022-10-07 18:22 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Divider weight={1} backgroundColor='background.transparentGray' />
Когда убрала weight={1}, то линия пропала (height стал равен 0)

2022-10-07 18:25 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +      <Box width='98%' maxWidth={[600, 790, 1920]}>
ну...да, как я тебе и говорил в предыдущих реквестах

2022-10-07 18:27 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Divider weight={1} backgroundColor='background.transparentGray' />
🤔 
ок, тогда оставь

2022-10-07 18:28 UTC, TFK70 commented on ui/theme/src/global.styles.tsx
> +        p {
Посмотри какие стили есть в dream-team, misik, VSBLE
Оставь только необходимые, которые есть на всех проектах. Своего сюда ничего не нужно лишнего добавлять, мы же не для того css-in-js используем чтобы все стили сюда прописывать

2022-10-10 07:19 UTC, TFK70 requested changes

2022-10-10 07:19 UTC, TFK70 commented on landing/entrypoints/renderer/package.json
> +    "@ui/theme": "workspace:0.0.1",
workspace зависимости в энтрипоинтах должны быть в devDependencies

2022-10-10 07:19 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
Идея нашего подхода к вёрстке в том, что у каждого элемента должен быть свой контейнер
Зачем это надо почитай [тут](https://ishadeed.com/article/building-real-life-components/) (серьёзно, почитай, это важно)

2022-10-10 07:19 UTC, TFK70 commented on ui/button/src/button.styles.ts
> +export const appearanceStyles = ({ theme, active }) => getAppearanceStyles(theme, active)
И раз уж эта итерация у тебя тоже пока не проходит, то используй для кнопки генератор
Пример есть [тут](https://github.com/torin-asakura/VSBLE/tree/master/ui/button). Генератор будет генерировать файл с appearance styles для кнопки на основе твоей темы

И да, реструктурируй button полностью по примеру из VSBLE, текущая структура слишком сложная, поэтому мы так больше не пишем

2022-10-10 11:13 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
Прочитала, я правильно поняла, что мне нужно к каждому компоненту <Text> добавить контейнер?

2022-10-10 11:14 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
А ты поняла что в статье-то написано? Зачем к каждому компоненту добавлять контейнер?

2022-10-10 11:29 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
Чтобы компонент не ломался при различных состояниях

2022-10-10 11:31 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
И вот здесь 
> Прочитала, я правильно поняла, что мне нужно к каждому компоненту добавить контейнер?

не правильно написала. Я имела ввиду это:

2022-10-10 11:37 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +              <Text
Не привязывайся к частностям. Это правило относится ко всем компонентам: к баттону, инпуту и тп

Но в целом да, суть такая

2022-10-10 13:03 UTC, eshevlyakova commented on ui/button/src/button.styles.ts
> +export const appearanceStyles = ({ theme, active }) => getAppearanceStyles(theme, active)
А в какой момент генератор будет генерировать файл с appearance styles? При запуске пакета?

2022-10-10 13:05 UTC, eshevlyakova commented on ui/button/src/button.styles.ts
> +export const appearanceStyles = ({ theme, active }) => getAppearanceStyles(theme, active)
Все я уже поняла))

2022-10-10 13:34 UTC, eshevlyakova commented on ui/button/src/button.styles.ts
> +export const appearanceStyles = ({ theme, active }) => getAppearanceStyles(theme, active)
У меня вопрос, а как задавать для разных разрешений разные падинги? В этом коде (для кнопок социальных сетей):
```typescript
const socialStyles = createShapeStyles({
  size: 56,
  rounding: prop('theme.radii.big') as unknown as number,
  paddingLeft: 16,
  paddingRight: 16,
})
```

2022-10-10 13:38 UTC, TFK70 commented on ui/button/src/button.styles.ts
> +export const appearanceStyles = ({ theme, active }) => getAppearanceStyles(theme, active)
Показывай разные кнопки

```jsx
<Layout display={['none', 'none', 'flex']}>
   <Button size='normal' />
</Layout>
<Layout display={['flex', 'flex', 'none']}>
   <Button size='small' />
</Layout>
```

2022-10-10 17:43 UTC, TFK70 requested changes
1. Дивайдер должен иметь ширину 1160px (и другие элементы в этом боке я так понимаю тоже не соответствуют размерам из дизайна)

![image](https://user-images.githubusercontent.com/62806448/194924326-be24dfb2-82e0-4d3a-b90f-771f53d8057e.png)

2. Насчёт навигации мой косяк: она должна растягиваться на всю ширину экрана, так что убери maxWidth

2022-10-11 08:52 UTC, TFK70 requested changes

2022-10-11 08:52 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +      <Box width='100%' maxWidth={[600, 790, '100%']}>
Вообще maxWidth можешь убрать
И не понимаю зачем maxWidth на мобилках

2022-10-11 08:52 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          <Box width={['100%', '95%', '83%']} maxWidth='1160px'>
Что за проценты-то опять? Я же просил их убрать, если они еще где-то есть - убери
Дай ему просто ширину в пикселях

2022-10-11 08:57 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          <Box width={['100%', '95%', '83%']} maxWidth='1160px'>
Если я поставлю просто ширину в px, то на экранах от 900px до 1160px верстка будет выглядеть некорректно (элемент больше самого окна):
<img width="1261" alt="Снимок экрана 2022-10-11 в 11 56 35" src="https://user-images.githubusercontent.com/79781486/195045686-f07c5fdb-50ae-4541-87ee-2e13b3e01ed3.png">

А благодаря процентам на разрешении 1920px и больше все выглядит как в дизайне, а если экран меньше то блок просто уменьшается

2022-10-11 09:58 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +          <Box width={['100%', '95%', '83%']} maxWidth='1160px'>
Так а зачем ты только дивайдеру эту ширину задаешь если у тебя весь контейнер должен быть 1160px?

2022-10-11 10:02 UTC, TFK70 requested changes

2022-10-11 10:02 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
1. У Column height руками не задаётся. Он по умолчанию 100% и всегда должен оставаться 100%
2. Зачем тебе опять minHeight?

2022-10-11 10:02 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +                  borderRadius='24px'
Из темы

2022-10-11 10:02 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +                  width='130px'
Пиши пожалуйста пиксели не строкой, а намбером: `width={130}`, следуй общему кодстайлу

2022-10-11 10:02 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +                <Box display={['none', 'none', 'block']}>
Почему block? Мы на флексах верстаем

2022-10-11 11:29 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
2. Почему опять, если оно и было так) Потому что если экран браузера будет слишком маленький, то верстка сломается (мы рассчитываем высоту блока от окна браузера), а так просто появится скролл

2022-10-11 11:35 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
Чтоб ты понимала: мы не используем minWidth и minHeight **совсем**. На misik они встречаются буквально в 2-3 местах, на VSBLE их вообще нет, а я говорю о проектах с вёрсткой, которая готова идти в прод. У тебя же всего один блок из лендинга у тебя за все это время встретился целый легион minWidth и minHeight.

Посмотри как тот же самый hero блок сделан в misik и сделай так же. Без minHeight.

2022-10-11 11:35 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
Прямо в инспекторе посмотри на блок, какие у него свойства

2022-10-11 11:42 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      minHeight={['520px', '630px', '500px']}
1.  Тогда я задам height блоку выше - <Box>, но мне прийдется задать тегу body или обертке #__next height: 100%. Иначе будет срабатывать minHeight:
<img width="1261" alt="Снимок экрана 2022-10-11 в 14 42 14" src="https://user-images.githubusercontent.com/79781486/195080785-c96ef747-64ba-42c5-a44c-3c901066d5b0.png">
Хорошо?

2022-10-11 14:50 UTC, TFK70 requested changes

2022-10-11 14:50 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
И ширина все еще не 1160...

![image](https://user-images.githubusercontent.com/62806448/195124280-704ae500-cfa4-4dd5-9860-127edcbccba2.png)

Такое чувство что я в пустоту эти комментарии про maxWidth оставляю, это же не просто так

2022-10-11 15:25 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
> Такое чувство что я в пустоту эти комментарии про maxWidth 

Я объясняла выше почему не могу убрать maxWidth.
Если я поставлю просто ширину в px, то на экранах от 900px до 1160px верстка будет выглядеть некорректно (контейнер залезает на соц сети):
<img width="1261" alt="Снимок экрана 2022-10-11 в 18 24 00" src="https://user-images.githubusercontent.com/79781486/195133274-42e6ebd0-c09e-4d75-99cb-4dcaa2d0dd86.png">


А благодаря процентам на разрешении 1920px и больше все выглядит как в дизайне, а если экран меньше то блок просто уменьшается

2022-10-11 15:27 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
Я могу оставить maxWidth?

2022-10-11 16:01 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
Так вот в чём дело, у тебя соцсети position absolute имеют

Абсолюты используются в крайних случаях, твои соцсети вполне себе помещаются в сетку, сделай этот блок на флексах и проблема уйдет. Никакой maxWidth оставлять не надо

2022-10-11 16:40 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
Я сделала соцсети без абсолюта, но верстка все равно сломалась, получается <Column> с соц сетями вылазит
<img width="1261" alt="Снимок экрана 2022-10-11 в 19 37 20" src="https://user-images.githubusercontent.com/79781486/195149771-a543a692-3cfe-40cf-8599-4c5e057ad2b9.png">
Сделать коммит или вернуть все как было?

2022-10-11 16:56 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Column justifyContent='end' width={['100%', '100%', '85%']} maxWidth={1160}>
> Абсолюты используются в крайних случаях

У меня появилась идея как можно реализовать без maxWidth, но мне нужен абсолют. Это считается как крайний случай?

2022-10-12 08:09 UTC, eshevlyakova commented
@TFK70
Я сделала по скелету, но теперь на разрешениях от 900px до 1300px верстка ломается:
<img width="813" alt="Снимок экрана 2022-10-12 в 11 02 43" src="https://user-images.githubusercontent.com/79781486/195285579-7826358f-9bd5-404a-ac6a-75a5b6fd592c.png">
И на экранах с 1300px до 1500px соц сети прижаты к названию:
<img width="813" alt="Снимок экрана 2022-10-12 в 11 04 41" src="https://user-images.githubusercontent.com/79781486/195285987-1a8f7e29-44de-4948-ab60-e0ee3607a939.png">
А из-за чего нельзя использовать maxWidth? Мне кажется в данной ситуации это самый оптимальный выход, у нас есть соответствие с дизайном и на экранах меньше, тоже все хорошо

2022-10-12 08:26 UTC, TFK70 commented
@eshevlyakova на скелетоне который я закинул такие проблемы были?

2022-10-12 08:56 UTC, TFK70 commented
@eshevlyakova а зачем ты его так сильно сжимаешь? Это что за устройство должно быть с таким вьюпортом? Смотри реальные разрешения: если на них всё в порядке - то зачем пытаться ломать сайт?

2022-10-12 09:01 UTC, eshevlyakova commented
@TFK70 
> Это что за устройство должно быть с таким вьюпортом?

Старые мониторы с разрешением 1024px

> то зачем пытаться ломать сайт?

Я думаю сайт на всех разрешениях не должен ломаться (кроме < 300px). К примеру человек решил сделать окно браузера поменьше и у него просто ломается сайт, так не должно быть)

И на моем разрешении соцсети прилипают к заголовку:
<img width="1280" alt="Снимок экрана 2022-10-12 в 12 00 46" src="https://user-images.githubusercontent.com/79781486/195299258-3c2ee1e0-6c96-4d69-b9ce-4705c9815379.png">

Почему нельзя для контейнера использовать maxWidth={1160}?

2022-10-12 16:47 UTC, eshevlyakova commented
@TFK70 
[Указала такую высоту](https://github.com/atls-academy/eshevlyakova.github.io/blob/27cd41e9c785f79c655cc67cee713c98d96d5afa/landing/fragments/landing-section-banner/src/banner.component.tsx#L15) потому что иначе на экранах высотой меньше 1080px выглядит некорректно (это достаточно большой процент). К примеру на моем это выглядело так:
<img width="1280" alt="Снимок экрана 2022-10-12 в 19 44 38" src="https://user-images.githubusercontent.com/79781486/195401011-c322baf7-7539-4020-8a15-2a1fb1a9013f.png">

А с помощью vh, высота высчитывается исходя из высоты экрана

2022-10-12 17:05 UTC, TFK70 commented
@eshevlyakova норм, а на моём вот так:

![image](https://user-images.githubusercontent.com/62806448/195404919-aefe358a-b12c-4454-ae33-05f63b98aa9e.png)

2022-10-12 17:16 UTC, eshevlyakova commented
@TFK70 
А должен весь экран закрывать? Просто height={1080} вообще не вариант, могу вернуть 95vh, тогда должен весь экран покрывать

2022-10-12 17:21 UTC, TFK70 commented
@eshevlyakova он должен соответствовать дизайну

Сейчас хедер у тебя имеет height 120px (норм), а основной блок имеет height 925px (не норм)

В сумме должно получаться 1080, у тебя 1045 с копейками. Если нужно адаптировать под более маленькие экраны - ок, но остальные вьюпорты не должны от этого страдать

2022-10-12 17:31 UTC, eshevlyakova commented
@TFK70 
Неправильно сделала, сейчас изменила высоту на 89vh. И получается при разрешении 1920x1080: header 120px и блок 960px, что соответсвует дизайну, а на экранах меньше тоже выглядит приемлемо:
<img width="1280" alt="Снимок экрана 2022-10-12 в 20 29 28" src="https://user-images.githubusercontent.com/79781486/195409339-c34302c1-a8b9-4ca3-aec7-e3b0ec32c8a8.png">
При скролле вниз появляется нижний отступ:
<img width="1280" alt="Снимок экрана 2022-10-12 в 20 30 39" src="https://user-images.githubusercontent.com/79781486/195409562-2e1fecf9-c71f-4f8a-bb71-282486b36295.png">

2022-10-12 18:30 UTC, TFK70 commented
@eshevlyakova пришёл ответ насчет проблемы с шириной блока

Нужно задать ему ширину в % чтобы он сжимался (как у тебя в общем было), но только учти что он должен по возможности иметь размер 1160px и не сжиматься раньше времени

2022-10-13 07:07 UTC, eshevlyakova commented
@TFK70 
Исправила, на 1920x1080 ширина как и в дизайне 1160px:
<img width="802" alt="Снимок экрана 2022-10-13 в 10 02 38" src="https://user-images.githubusercontent.com/79781486/195525110-79856237-d3c7-415b-9b2f-4412211bde86.png">
А на экранах меньше блок сжимается:
<img width="1280" alt="Снимок экрана 2022-10-13 в 10 03 16" src="https://user-images.githubusercontent.com/79781486/195525235-001bbd91-391c-4f82-a4bf-2236fb52799d.png">

2022-10-13 08:01 UTC, TFK70 requested changes

2022-10-13 08:25 UTC, TorinAsakura commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', '90%']}>
Дело даже не в том, что такого у нас нигде нет, а в том, что выставляя проценты, ты не можешь контролировать поведение важных для ЦА элементов вёрстки.

2022-10-13 13:28 UTC, eshevlyakova commented
@TFK70 
> Нужно задать ему ширину в % чтобы он сжимался (как у тебя в общем было)

У меня был maxWidth, без него я не могу ограничить ширину в процентах. Я могу использовать это свойство? 

> выставляя проценты, ты не можешь контролировать поведение важных для ЦА элементов вёрстки

Я понимаю это, но сейчас мы же проценты совместно утвердили

2022-10-13 13:37 UTC, TFK70 commented
@eshevlyakova 

> У меня был maxWidth, без него я не могу ограничить ширину в процентах. Я могу использовать это свойство?

А есть другие предложения?

> Я понимаю это, но сейчас мы же проценты совместно утвердили

Да, но я не помню чтобы мы утвердили ширину блока в 2к пикселей на вайдскрин мониторах, вместо 1160

2022-10-13 14:11 UTC, TFK70 requested changes
Я думаю он должен находиться по центру

![image](https://user-images.githubusercontent.com/62806448/195620579-837d09ba-d423-424a-a315-cf7fce223f7f.png)

2022-10-13 14:28 UTC, TFK70 requested changes

2022-10-13 14:28 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', 1289]}>
Ты подбором это значение вычислила? У тебя тогда на вайдскринах мейн блок будет тоже 1289, а не 1160

2022-10-13 14:34 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', '90%']} maxWidth={1160}>
Тогда зачем мы используем проценты? Именно 90% позволяют нормально отображаться блоку на экранах меньше

2022-10-13 15:22 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', '90%']} maxWidth={1160}>
1. Мы уже выяснили что не позволяет - у тебя размеры блока все-равно не соответствуют дизайну
2. https://github.com/atls-academy/eshevlyakova.github.io/pull/11#discussion_r994321000

100%/0% - это считай исключение, так как ты точно можешь сказать без доп вычислений какая ширина будет у блока

2022-10-13 15:28 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', 1289]}>
Блок с divider и текстом ниже будет 1160

2022-10-13 15:39 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', 1289]}>
А я что-то про дивайдер или про блок с текстом спросил?

2022-10-13 15:40 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Box width={['100%', '100%', 1289]}>
Я сказал что у тебя мейн блок будет иметь размер 1289, а не 1160, и спросил как ты получила эту цифру

2022-10-13 16:38 UTC, TFK70 requested changes

2022-10-13 16:38 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Layout flexBasis={[24, 24, 48]} flexShrink={0} />
Зачем тут flexShrink?

2022-10-13 16:38 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Layout flexBasis={[24, 24, 48]} flexShrink={0} />
И тут?

2022-10-13 16:38 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Layout flexBasis={[24, 24, 48]} flexShrink={0} />
И тут

2022-10-13 16:38 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +      <Layout flexBasis={[0, 0, 60]} flexShrink={0} />
И тут

2022-10-13 16:43 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Layout flexBasis={[24, 24, 48]} flexShrink={0} />
Во всех этих случаях, без flexShrink на моем разрешении отступы сжимаются

2022-10-13 16:44 UTC, eshevlyakova commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +        <Layout flexBasis={[24, 24, 48]} flexShrink={0} />
Без этих flexShrink, верстка выглядит так:
<img width="1280" alt="Снимок экрана 2022-10-13 в 19 44 30" src="https://user-images.githubusercontent.com/79781486/195656243-42e61f16-47a1-4970-a517-18d4c5ba5800.png">

2022-10-13 17:02 UTC, TFK70 approved these changes

2022-10-17 23:39 UTC, TorinAsakura commented on .gitignore
> +landing/entrypoints/renderer/.next
можно просто указать .next

2022-10-17 23:43 UTC, TorinAsakura approved these changes

2022-10-17 23:44 UTC, merged