feat/landing-step-2
atls-academy/eshevlyakova.github.io pull request #17
Opened 2022-10-17 16:55 UTC by eshevlyakova

2022-10-17 17:13 UTC, TFK70 requested changes
1. Фон в хиро режется

![image](https://user-images.githubusercontent.com/62806448/196240082-616e9df7-bc05-4112-bdf6-d420361b21ee.png)

2. Текст во второй секции не центрируется на вайдскринах

![image](https://user-images.githubusercontent.com/62806448/196240165-1b211f83-9e64-4eb8-b97c-557c10e0d5f8.png)

2022-10-17 17:13 UTC, TFK70 commented on landing/fragments/landing-section-banner/src/banner.component.tsx
> +                    border='1px solid'
Должно быть в теме
theme/borders

2022-10-17 17:13 UTC, TFK70 commented on landing/fragments/landing-section-description/package.json
> +    "@ui/theme": "0.0.1"
workspace

2022-10-17 17:13 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +  <Box background={theme.backgrounds.blueAndPurpleGradient}>
И......зачем нам тогда emotion? Мы так не делаем. Нигде и никогда.

2022-10-17 17:13 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +import { theme }            from '@ui/theme'
Нигде тема так не импортируется

2022-10-17 17:13 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +import { Layout }           from '@ui/layout/src'
`/src` в конце

2022-10-17 17:13 UTC, TFK70 commented on landing/pages/index-page/src/index.page.tsx
> +        theme.backgrounds.mobileBannerBlockBackground,
Тоже убирай

2022-10-17 17:13 UTC, TFK70 commented on landing/pages/index-page/package.json
> +    "@ui/theme": "0.0.1"
Ну и тема как зависимость уже будет не нужна, когда ты её использование пофиксишь

2022-10-17 17:13 UTC, TFK70 commented on ui/button/src/button.component.tsx
> +import { appearanceStyles } from './styles/appearance/button.appearance-styles'
Импорт кривой, сделай через индексы как и везде

2022-10-17 17:13 UTC, TFK70 commented on ui/theme/src/theme/backgrounds.ts
> +    'url("http://dev.eshevlyakova.ru/academy/bg-section-1.png"), linear-gradient(180deg, #3D24EC 0%, rgba(61, 36, 236, 0) 100%), radial-gradient(33.16% 148.4% at 100% 100%, #3909F7 0%, rgba(104, 82,
Храни все изображения локально и подгружай через next/image
Ты же не будешь на наших продовых проектах свой бакет использовать?

2022-10-18 11:25 UTC, eshevlyakova commented
@TFK70 
А как это реализуется, к примеру я пишу [название размера шрифта](https://github.com/atls-academy/eshevlyakova.github.io/blob/master/landing/fragments/landing-section-banner/src/banner.component.tsx#L31) из темы, а в браузер подставляется число которое [соответствует данному значению](https://github.com/atls-academy/eshevlyakova.github.io/blob/master/ui/theme/src/theme/fontSizes.ts)?

2022-10-18 11:45 UTC, TFK70 commented
@eshevlyakova меня больше интересует почему ты об этом спрашиваешь. У меня сейчас 2 вопроса:

1. Это действительно так неочевидно?
2. У тебя это работает как-то по-другому/не работает вообще?

2022-10-18 12:49 UTC, eshevlyakova commented
@TFK70 

1. Все уже поняла
2. У меня все работает. Как сделать так, чтобы для свойства [background](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-2/landing/pages/index-page/src/index.page.tsx#L18) фон брался из файла [backgrounds.ts](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-2/ui/theme/src/theme/backgrounds.ts)?

2022-10-18 12:55 UTC, TFK70 commented
@eshevlyakova ну, видимо не поняла

https://emotion.sh/docs/theming - открывай, читай

2022-10-18 15:48 UTC, eshevlyakova commented
@TFK70 
> что? Ты же меня вообще другое спросила

Мне нужно чтобы значение для свойства background бралось из файла backgrounds.ts и для каждого разрешения было свое значение. Но в [этой статье](https://emotion.sh/docs/theming) я не нашла решение

2022-10-19 12:57 UTC, eshevlyakova commented on landing/fragments/landing-section-description/src/description.component.tsx
> +        <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
Чтобы на разрешении 1280px (macbook 13) боковые отступы сжимались. Без них блок выглядит вот так:
<img width="697" alt="Снимок экрана 2022-10-19 в 15 56 02" src="https://user-images.githubusercontent.com/79781486/196696828-3db44636-bb8e-472e-8cf8-b8a2e8a96734.png">

С ними вот так:
<img width="697" alt="Снимок экрана 2022-10-19 в 15 56 38" src="https://user-images.githubusercontent.com/79781486/196696976-b591c415-3d20-4d2e-9e53-1ebedda9db37.png">

2022-10-19 13:31 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +        <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
Окей, тогда откуда взялась цифра 5?

2022-10-19 13:37 UTC, eshevlyakova commented on landing/fragments/landing-section-description/src/description.component.tsx
> +        <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
Ну значение этого свойства указывает на сколько частей будет уменьшаться в данном случае отступ. И я пробывала значения меньше, они не подходили. К примеру flexShrink: 2 выглядит так:
<img width="796" alt="Снимок экрана 2022-10-19 в 16 37 14" src="https://user-images.githubusercontent.com/79781486/196706874-5c4e3890-6e31-4864-8196-ff555a53b67c.png">
Только при значении 5, блок выглядит как нужно

2022-10-19 22:01 UTC, TFK70 requested changes

2022-10-19 22:01 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +      <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
Просто "к слову", место в styled system где формируются дефолтные брейкпоинты, для общего развития - https://github.com/styled-system/styled-system/blob/master/packages/core/src/index.js#L29
Можешь порезолвить этот реквест как чекнешь

2022-10-20 06:56 UTC, eshevlyakova commented on landing/fragments/landing-section-description/src/description.component.tsx
> +      <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
> порезолвить этот реквест

А что это значит?

2022-10-20 07:45 UTC, TFK70 commented on landing/fragments/landing-section-description/src/description.component.tsx
> +      <Layout flexBasis={[20, 20, 230]} flexShrink={5} />
![image](https://user-images.githubusercontent.com/62806448/196887882-32296646-93fd-44e6-8933-0bf7475bb2f9.png)

2022-10-20 08:31 UTC, eshevlyakova commented on landing/fragments/landing-section-description/src/description.component.tsx
> +            display='inline'
Что бы весь контент внутри располагался друг за другом, как строка текста. Без этого свойства, блок выглядит так:
<img width="762" alt="Снимок экрана 2022-10-20 в 11 28 34" src="https://user-images.githubusercontent.com/79781486/196897404-2c335678-fbe7-40b6-8287-7fdcaa8ffffc.png">

2022-10-20 10:40 UTC, TFK70 approved these changes
И пока ждём резолва по фону в хиро

2022-10-20 13:11 UTC, TFK70 commented
@eshevlyakova разделённые  фон и symbol - https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=505%3A334

У symbol сверху есть дефекты, их не должно быть видно, поэтому symbol должен быть прикреплен к верхней границе

Сам фон растягивай

2022-10-20 16:34 UTC, eshevlyakova commented
@TFK70 
<img width="1280" alt="Снимок экрана 2022-10-20 в 19 32 27" src="https://user-images.githubusercontent.com/79781486/197006510-0d0cc056-bc89-4438-a9d7-cfe50e2fe666.png">
У фона справа не такой цвет, как был изначально тут в дизайне:
<img width="618" alt="Снимок экрана 2022-10-20 в 19 33 26" src="https://user-images.githubusercontent.com/79781486/197006713-bb768234-259a-4038-9388-c8a32e430c6f.png">

2022-10-21 12:54 UTC, TFK70 commented
@eshevlyakova https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=505%3A334

1. Обновился фон
2. Снизу к фону в hero добавился дополнительный блок с цветом, как у следующего, чтобы они сливались
3. Цвет второго блока тоже упростился

2022-10-21 15:09 UTC, TFK70 approved these changes
👌

2022-10-21 15:24 UTC, TorinAsakura approved these changes

2022-10-21 15:24 UTC, merged