feat/landing-step-3
atls-academy/eshevlyakova.github.io pull request #21
Opened 2022-10-26 10:56 UTC by eshevlyakova

2022-10-27 11:24 UTC, eshevlyakova commented
@TFK70 
Обновила пакет @ui/icons, но у меня также для svg тега прописывается [ширина и высота 1em, вместо px](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/icons/src/ComputerMouseIcon.tsx#L12). Хотя в [исходных svg изображениях px](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-3/ui/icons/icons/ComputerMouse.svg?short_path=aab91d2#L1). 
Я удаляла папку icons/src и заново запускала команду  `yarn workspace @ui/icons run generate-icons`, но ничего не изменилось. Все данные копипастила [отсюда](https://github.com/torin-asakura/shdvor/tree/master/ui/icons). Как это можно исправить?

И я заметила в [ветке master также em](https://github.com/atls-academy/eshevlyakova.github.io/blob/master/ui/icons/src/ComputerMouseIcon.tsx#L12)

2022-10-27 12:11 UTC, TFK70 commented
@eshevlyakova извини, это нормальное поведение svgr, оставляй как есть, у тебя всё в порядке

2022-10-27 13:36 UTC, eshevlyakova commented
@TFK70 
[Ошибка TypeCheck](https://github.com/atls-academy/eshevlyakova.github.io/pull/21/checks?check_run_id=9139336709)
Я гуглила эту ошибку и в качестве решения предложили прописать "skipLibCheck": true в tsconfig.json, но это не помогло
Swiper я использую только [в этом фрагменте](https://github.com/atls-academy/eshevlyakova.github.io/tree/feat/landing-step-3/landing/fragments/landing-section-courses)
Как исправить эту ошибку?

2022-10-28 14:45 UTC, TFK70 requested changes

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +              <Box
То, что у линка есть флексовый контейнер - это верно, но то, что происходит внутри - неверно.
У тебя вложенность такая: блок->текст->блок->текст, а должна быть такая: блок->текст

Блок - это блочный элемент, в твоём случае `div`
Текст - это строчный элемент, в твоём случае `span` и `a`

В общем, тебе нужно избавиться от лишней вложенности, стилизовать текст через a и не плодить лишние контейнеры внутри а

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +            <Link href='/' width={217}>
И у нас SPA. Ты используешь дефолтную ссылку, которая сделает полную перезагрузку страницы при переходе. Тебе нужна NextLink

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-hero/package.json
> +    "@types/react": "17.0.47"
Зачем ты в каждом пакете фиксишь эту зависимость? У тебя есть resolutions в корневом пекедже, укажи её там и всё

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +            <Column width='100%'>
У тебя очень сложная вложенность получилась: Row->Column->Column->Box->Column

Расскажи какой блок у тебя за что отвечает

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +              <Box>
Йоумаё, ну ты ж на реакте пишешь, неужели ты скопипастила компонент на 50 строк несколько раз, раздула файл с вёрсткой почти на 1000 строк и тебе норм? Вынеси карточку в компонент обязательно, никогда больше так не делай

2022-10-28 14:45 UTC, TFK70 commented on landing/fragments/landing-section-courses/package.json
> +    "swiper": "^8.3.1"
Зачем тут свайпер?

2022-10-28 14:45 UTC, TFK70 commented on ui/icons/replacements.ts
>   * */
Зачем ты это оставила? И зачем тебе вообще replacements если у тебя ни одного реплейсмента нет? Следи за чистотой на проекте, не разводи бардак

2022-10-31 09:58 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +            <Column width='100%'>
Я немного исправила код:
<img width="870" alt="Снимок экрана 2022-10-31 в 12 44 12" src="https://user-images.githubusercontent.com/79781486/198979024-1a87a816-d157-415b-907b-d7f6490ddd9c.png">
И получилось Row -> Column
Row - выравнивает контент по центру
Column - фиксирует ширину контейнера и располагает контент вертикально

Этот Box:
<img width="870" alt="Снимок экрана 2022-10-31 в 12 46 09" src="https://user-images.githubusercontent.com/79781486/198979464-be3d288a-6095-4860-8edc-74b13faaa42c.png">
Нужен для того чтобы задать горизонтальные отступы. Я не могла задать отступы для всей секции сразу, потому что на мобилке у слайдера правого отступа нет, но для всей секции он есть:
<img width="281" alt="Снимок экрана 2022-10-31 в 12 58 15" src="https://user-images.githubusercontent.com/79781486/198981881-0120930a-5537-4d71-948c-99b3a4c72cc6.png">

2022-11-01 09:01 UTC, TFK70 requested changes

2022-11-01 10:28 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +            <Column justifyContent='space-between'>
Первый Column для вертикальных отступов и контента, а второй Column это сам контент и так как у карточки задана высота, использую свойство justifyContent='space-between', чтобы один элемент был вверху, другой внизу:
<img width="803" alt="Снимок экрана 2022-11-01 в 13 27 30" src="https://user-images.githubusercontent.com/79781486/199213469-fb5f9bef-833e-4e53-9107-ba26d7a68fe4.png">

2022-11-01 10:34 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
Я до этого писала о том, что на мобилке у слайдера нет справа отступов из-за этого в данном случае я прописываю для каждой карточки горизонтальный отступ отдельно. То есть в первом Box отступы по краям для маленьких экранов и планшетов, а в Background именно отступы для контента карточки

2022-11-01 10:39 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                <Button size='normalAllMaterials' variant='darkPurpleBlue'>
Потому что так Button растягивается на нужную ширину (253px). У этой кнопки достаточно большой отступ между текстом и картинкой:
<img width="322" alt="Снимок экрана 2022-11-01 в 13 37 54" src="https://user-images.githubusercontent.com/79781486/199215186-fa461ef9-a1f7-426b-ab81-a96df2af60cf.png">

2022-11-01 11:05 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                <Button size='normalAllMaterials' variant='darkPurpleBlue'>
Я спросил про Column, а не про width
Ты на рандом эти компоненты используешь?

2022-11-01 11:06 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +            <Column justifyContent='space-between'>
Второй Column ведь лишний, ты можешь без него эти элементы вертикально спозиционировать

2022-11-01 11:20 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                <Button size='normalAllMaterials' variant='darkPurpleBlue'>
> Я спросил про Column, а не про width

Потому что только при flex-direction: column кнопка растягивается на всю доступную ширину. Если вместо Column использую Box, то кнопка выглядит так: 
<img width="322" alt="Снимок экрана 2022-11-01 в 14 19 10" src="https://user-images.githubusercontent.com/79781486/199221715-e3c43ae7-051c-4094-80a8-4f61c9d12716.png">

2022-11-01 11:22 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +            <Column justifyContent='space-between'>
Убрать свойство justifyContent='space-between' и сделать через Layout flexBasis?

2022-11-01 11:49 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +            <Column justifyContent='space-between'>
А, извини, проглядел space-between

Тогда да, оставь так

2022-11-01 11:49 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
> Я до этого писала о том, что на мобилке у слайдера нет справа отступов

Дай линк пожалуйста, мне проблема не совсем понятна

2022-11-01 12:07 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                <Button size='normalAllMaterials' variant='darkPurpleBlue'>
Ну потому что твоей кнопке тоже нужно задать какой-то размер. Это же семантически неправильно то что у тебя единственный элемент в Column

Поставь кнопке проп fill

2022-11-01 12:08 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
https://github.com/atls-academy/eshevlyakova.github.io/pull/21#discussion_r1009230237
В этом комментарии я объясняла зачем нужен Box, с помощью него я задаю горизонтальные отступы для этих элементов:
<img width="599" alt="Снимок экрана 2022-11-01 в 15 07 24" src="https://user-images.githubusercontent.com/79781486/199229016-4c3d31fd-e416-400b-89a9-2691909fe987.png">

А для карточек я задаю отдельно, как раз таки в первом Box

2022-11-01 13:23 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
@eshevlyakova так тебе наверное просто нужно задать width для слайдера? Это уже предусмотрено в `@atls-ui-parts/swiper`, ты этим пользуешься?

2022-11-01 13:42 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
> так тебе наверное просто нужно задать width для слайдера?

Так если я задам width для слайдера, то как это поможет убрать отступ справа (который задан для всей секции)? Я смотрела примеры работ со слайдерами и там везде задана ширина, но там и слайдер выровнен по центру (как и все элементы секции)

2022-11-01 13:46 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                        <Box order={[5, 5, 0]} height={[64, 100, 240]} width={[64, 100, 240]}>
В данном случае первый первый Box это контейнер для адаптива на планшетах и телефонах:
<img width="363" alt="Снимок экрана 2022-11-01 в 16 45 15" src="https://user-images.githubusercontent.com/79781486/199248128-a756d731-1291-4f7b-b62b-5e23381a98fc.png">
А второй Box для картинки

2022-11-01 13:47 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +        <Layout flexBasis={[16, 28, 40]} />
@eshevlyakova перестань прикладывать пожалуйста скриншоты в таких ситуациях, я не понимаю про какие компоненты и отступы ты говоришь. В твоём последнем сообщении я вообще ничего не понял

Ссылки на фигму и на код

2022-11-01 13:58 UTC, TFK70 requested changes

2022-11-01 13:58 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +  </Background>
У тебя компонент получился на 347 строк

Почему ты не разбила его на маленькие компоненты? Так же невозможно работать

2022-11-01 16:30 UTC, eshevlyakova commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                    backgroundColor='white'
А есть какие-то примеры?

2022-11-01 16:42 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/courses.component.tsx
> +                    backgroundColor='white'
Есть демонстрация концепта в [input](https://github.com/atls/uikit/tree/master/ui-parts/input/src/attachment)

[Использование](https://github.com/torin-asakura/VSBLE/tree/master/ui/input/src/search-attachment). Он, например, внутри инпута добавляет иконку с лупой

2022-11-03 14:35 UTC, TFK70 requested changes

2022-11-03 14:35 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/cards/card-desc/card-desc.component.tsx
> +import { Layout }        from '@ui/layout/src'
Следи за форматом инпутов пж, не оставляй `/src` в конце

2022-11-03 14:35 UTC, TFK70 commented on landing/fragments/landing-section-courses/src/training-details/training-details.component.tsx
> +import { Layout }           from '@ui/layout/src'
Рекурсивной заменой по проекту пройдись, чтобы ото всюду `/src` убрать

2022-11-03 14:35 UTC, TFK70 commented on landing/fragments/landing-header/src/header.component.tsx
> +              iconSvg={<ArrowBottomIcon />}
Тут немного не понял назначение пропов: за что отвечает `icon`?

2022-11-04 07:24 UTC, TFK70 approved these changes

2022-11-04 09:09 UTC, TorinAsakura approved these changes

2022-11-04 09:09 UTC, merged