feat/landing-step-4
atls-academy/eshevlyakova.github.io pull request #29
Opened 2022-11-07 17:03 UTC by eshevlyakova

2022-11-08 13:11 UTC, TFK70 requested changes
Норм, но у тебя блок с бэкдроп фильтром появляется слишком резко при открытии дроуера в навигейшне, добавь ему плавности

2022-11-08 13:37 UTC, eshevlyakova commented
@TFK70 
> у тебя блок с бэкдроп фильтром появляется слишком резко при открытии дроуера в навигейшне

Ты про этот фон?
<img width="760" alt="Снимок экрана 2022-11-08 в 16 36 17" src="https://user-images.githubusercontent.com/79781486/200578949-e2b10cc5-80c5-468a-b465-b941cf72c320.png">

2022-11-08 13:37 UTC, TFK70 commented
@eshevlyakova да, сори, забыл скрин сделать

2022-11-11 20:49 UTC, TorinAsakura approved these changes

2022-11-11 20:50 UTC, merged