feat/landing-step-6
atls-academy/eshevlyakova.github.io pull request #34
Opened 2022-11-16 10:02 UTC by eshevlyakova

2022-11-16 10:45 UTC, TFK70 requested changes

2022-11-16 10:45 UTC, TFK70 commented on landing/fragments/landing-process-creation/package.json
> +    "typescript": "^4.8.4"
Зачем тут тайпскрипт?

2022-11-16 10:45 UTC, TFK70 commented on landing/fragments/landing-process-creation/package.json
> +    "@types/node": "^18.7.14",
Очень много мусорных зависимостей, почисти все фрагменты от них

2022-11-16 10:45 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +  const SliderControlsExporter = ({ swiper, setSwiper }) => {
`ControlsExporter` есть в `@atls-ui-parts/swiper`

2022-11-16 10:45 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
Не советую так делать с моками

У тебя, кстати, по этой причине возникает hydration error: html который у тебя сгенерировался на сервере не соответствует html в браузере, потому что ты генерируешь этот контент на стороне клиента

Сделай для этого кастомный хук `useSlides`, откуда будет приходить контент для слайдера

2022-11-16 10:45 UTC, TFK70 commented on ui/icons/replacements.ts
> +/**
Это полотно можно убрать если что

2022-11-16 11:16 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/package.json
> +    "typescript": "^4.8.4"
Если убираю и запускаю, то в консоли ошибка:
```shell
error - ../../../../.yarn/cache/@formatjs-ecma402-abstract-npm-1.11.1-174e729a12-e0321ba103.zip/node_modules/@formatjs/ecma402-abstract/utils.js (87:0) @ invariant
Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
null

```

2022-11-16 11:45 UTC, TFK70 commented on landing/fragments/landing-process-creation/package.json
> +    "typescript": "^4.8.4"
Почитай еще раз про пиры, ошибка с ними связана
Там как раз разбиралось на примере этой ошибки

2022-11-16 14:37 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/package.json
> +    "typescript": "^4.8.4"
У меня в [dependencies интл есть](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-6/landing/entrypoints/renderer/package.json#L19), а [в фрагменте в peerDependencies](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-6/landing/fragments/landing-process-creation/package.json#L30) интл тоже прописан

2022-11-16 17:24 UTC, TFK70 commented on landing/fragments/landing-process-creation/package.json
> +    "typescript": "^4.8.4"
У тебя у некоторых родителей отсутствует react-intl в peerDependencies, смотри внимательнее

2022-11-17 08:08 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
А есть какие-то примеры создания? 
Просто я прочитала документацию, поняла что это и зачем, но не понимаю как реализовать мой хук

2022-11-17 08:29 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
А зачем тут примеры? Просто сделай функцию которая возвращает какое-то значение, и это значение подставляй сюда

2022-11-17 09:04 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
> Просто сделай функцию которая возвращает какое-то значение

Но у нее же должен еще использоваться хук useState?

2022-11-17 09:08 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
Зачем? Почему должен?

2022-11-17 09:35 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={faker.image.cats()} srcMobileImage={faker.image.cats()} />
> Зачем? Почему должен?

Во всех примерах создания кастомных хуков это было

> которая возвращает какое-то значение

А на основе чего будет возвращаться значение? 
Функция должна принимать параметр, что-то делать и возвращать значение, которое я к примеру вставляю [сюда](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-6/landing/fragments/landing-process-creation/src/slider/slider.component.tsx#L53) в атрибуты?

2022-11-17 22:19 UTC, TFK70 requested changes

2022-11-17 22:19 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
Так делать не совсем правильно: твой хук уже подразумевает возврат картинки, тогда зачем её прописывать в аргументах?

2022-11-17 22:19 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +  const useSlides = (path) => {
И лучше вынести его в отдельный файл

2022-11-18 07:01 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
Ты про этот фрагмент: `useSlides(faker.image.cats())`?

2022-11-18 09:00 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
да

2022-11-18 09:02 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
Я же с помощью этого хука не только картинку рендерю, но еще и [текст](https://github.com/atls-academy/eshevlyakova.github.io/blob/feat/landing-step-6/landing/fragments/landing-process-creation/src/slider/slider.component.tsx#L103)

2022-11-18 11:31 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
С текстом та же история абсолютно
Твой хук уже должен заниматься тем, что предоставляет тебе готовый контент. В чём тогда его смысл, если ты этот контент прокидываешь снаружи?

2022-11-18 11:37 UTC, eshevlyakova commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
Тогда хук useSlides должен возвращать текст и картинку?

2022-11-18 11:51 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +              srcImage={useSlides(faker.image.cats())}
Либо так, либо создай 2 разных хука: один для текста, второй для картинки

2022-11-18 14:51 UTC, TFK70 requested changes

2022-11-18 14:51 UTC, TFK70 commented on landing/fragments/landing-process-creation/src/slider/slider.component.tsx
> +            <SlideImage srcImage={useImage()} srcMobileImage={useImage()} />
так не делают с хуками обычно
Объяви в теле компонента результат `const image = useImage()`
То, что у тебя будет работать, но это немного не соответствует нашему кодстайлу

2022-11-18 15:44 UTC, TFK70 approved these changes

2022-11-19 12:23 UTC, TorinAsakura approved these changes

2022-11-19 21:50 UTC, merged